name: Test

on: [push]

'lint-python':
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Lint Python code in plugins'
        run: |
          echo 'OK'
