name: Update Readme
on:
  push:
    branch:
      - master
    paths:
      - README.md

jobs:
  'update-documentation':
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Hub Description Update for BASE
      uses: peter-evans/dockerhub-description@v2.1.1
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${{secrets.DOCKER_IMAGE}}
        README_FILEPATH: README.md
