name: Update Readme
on:
  push:
    branch:
      - master
    paths:
      - README.md

jobs:
  'update-documentation':
    runs-on: ubuntu-latest
    steps:
    - name: Docker Hub Description Update for BASE
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: avdteam/base
        README_FILEPATH: README.md
